### PR TITLE
fixes queries to azure_log_alert table

### LINKED ISSUE #202: Fix CIS v2.0.0 5.2.X by replacing alert.location = 'global' & removing additional alert.condition for 'resourceType'
**Describe the bug**
None of 5.2.1-5.2.10 checks work.
It appears to be related to the fact the queries to `azure_log_alert` table filter the alarm rules by location set to `Global` (one example: https://github.com/turbot/steampipe-mod-azure-compliance/blob/v0.31/regulatory_compliance/monitor.sp#L265), while the `location` and `region` values in the table are lower-case.

```SQL
+--------------------------------------+----------+--------+--------------------------------------------------------------------------------------------------------------------------------->
| type                                 | location | region | condition                                                                                                                       >
+--------------------------------------+----------+--------+--------------------------------------------------------------------------------------------------------------------------------->
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Sql/servers/firewallRules/write","field":"operatio>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"microsoft.network/publicipaddresses","field":"resourceType"}>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Security","field":"category"},{"equals":"Microsoft.Security/securitySolutions/delete","field":"operationNam>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Authorization/policyAssignments/write","field":"op>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Sql/servers/firewallRules/delete","field":"operati>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Authorization/policyAssignments/delete","field":"o>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Network/publicIPAddresses/write","field":"operatio>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.ClassicNetwork/networkSecurityGroups/delete","fiel>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Security","field":"category"},{"equals":"Microsoft.Security/securitySolutions/write","field":"operationName>
| Microsoft.Insights/ActivityLogAlerts | global   | global | {"allOf":[{"equals":"Administrative","field":"category"},{"equals":"Microsoft.Network/networkSecurityGroups/write","field":"oper>
+--------------------------------------+----------+--------+--------------------------------------------------------------------------------------------------------------------------------->
(END)

```

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
v0.31

**To reproduce**
- create activity log alarm rules as described in the CIS Benchmark document
- run `steampipe --mod-location steampipe-mod-azure-compliance check benchmark.cis_v200_5_2`
- none of the checks is passing

**Expected behavior**
All checks should pass. 

**Additional context**

After changing `alert.location = 'Global'` to `alert.location = 'global'` the checks appear to be passing validation

### PR DESCRIPTION
**Pull request by KingBrewer**
### Checklist
- [x] Issue(s) linked

Resolves #202

### CODE REVIEW

**Comment by KingBrewer** [comment]
@rajlearner17 since the PR does not fix all the issues with section 5.2, specifically the contentious AND statements that check `resourceType` despite not being a part of audit procedure, please look at the comprehensive fix here: https://github.com/turbot/steampipe-mod-azure-compliance/compare/main...KingBrewer:cis-fix-5.2.x-2?expand=1

I tested it with the **removed conditions** and all the rules now fire correctly:

```
$ steampipe --mod-location steampipe-mod-azure-compliance check benchmark.cis_v200_5_2
```

```
| | 
5.2 Monitoring using Activity Log Alerts .................. 0 / 10 [==========]
| 
+ 5.2.1 Ensure that Activity Log Alert exists for Create P… 0 /  1 [=         ]
| | 
| OK   : Activity log alert exists for create policy as… Dev - Azure
| 
+ 5.2.2 Ensure that Activity Log Alert exists for Delete P… 0 /  1 [=         ]
| | 
| OK   : Activity log alert exists for delete policy as… Dev - Azure
| 
+ 5.2.3 Ensure that Activity Log Alert exists for Create o… 0 /  1 [=         ]
| | 
| OK   : Activity log alert exists for create or update… Dev - Azure
| 
+ 5.2.4 Ensure that Activity Log Alert exists for Delete N… 0 /  1 [=         ]
| | 
| OK   : Activity log alert exists for delete Network S… Dev - Azure
| 
+ 5.2.5 Ensure that Activity Log Alert exists for Create o… 0 /  1 [=         ]
| | 
| OK   : Activity log alert exists for create or update… Dev - Azure
| 
+ 5.2.6 Ensure that Activity Log Alert exists for Delete S… 0 /  1 [=         ]
| | 
| OK   : Activity log alert exists for delete Security … Dev - Azure
| 
+ 5.2.7 Ensure that Activity Log Alert exists for Create o… 0 /  1 [=         ]
| | 
| OK   : Activity Log Alert exists for Create or Update… Dev - Azure
| 
+ 5.2.8 Ensure that Activity Log Alert exists for Delete S… 0 /  1 [=         ]
| | 
| OK   : Activity Log Alert exists for Delete SQL Serve… Dev - Azure
| 
+ 5.2.9 Ensure that Activity Log Alert exists for Create o… 0 /  1 [=         ]
| | 
| OK   : Activity Log Alert exists for Create or Update… Dev - Azure
| 
+ 5.2.10 Ensure that Activity Log Alert exists for Delete … 0 /  1 [=         ]
  | 
  OK   : Activity Log Alert exists for Delete Public IP… Dev - Azure
| | 

Summary
OK ............................................................ 10 [==========]
SKIP ........................................................... 0 [          ]
INFO ........................................................... 0 [          ]
ALARM .......................................................... 0 [          ]
ERROR .......................................................... 0 [          ]
TOTAL ..................................................... 0 / 10 [==========]
```

**Comment by rajlearner17** [comment]
@KingBrewer, I appreciate your finding and the PR on this issue 👍 

We are wondering whether the Azure API response for `location` has changed from `Global` to `global` since we had this query developed. As I remember, we came across a few scenarios long back on this. We are testing a bit; expect us to revert soon.
Cheers!

**Comment by KingBrewer** [comment]
It might be. Azure API is known to be a bit chaotic with regards to case sensitivity, among all other things :) 
But please also check my other comment, with regard to the `resourceType`. Only after this commit https://github.com/turbot/steampipe-mod-azure-compliance/commit/0651b032071144969fdb92b71eab5afa5122c33a the checks appear to be firing correctly

**Comment by rajlearner17** [comment]
@KingBrewer Thanks for pointing out other cases; we validated the `and alert.condition -> 'allOf' @> '[{"field": "resourceType", "equals":......` condition in section 5.2.x, which seems to be an additional check but does not change the nature of the outcome after removing it. But it makes sense to follow strict CIS document steps. Its fair to include the changes in the same PR. 

We are also good to have `location` change. Please proceed and update the PR

CC @khushboo9024

**Comment by KingBrewer** [comment]
@rajlearner17 the commit [2d3b5ba](https://github.com/turbot/steampipe-mod-azure-compliance/pull/203/commits/2d3b5bae3a84c57d77746ef7f568636d83c562af) was added to the PR

**Review by khushboo9024 — APPROVED** [review]

**Pull request merged**
